* Cloud Native Devops with Kubernetes
* Ch 2 First Steps with Kubernetes
  #+begin_src sh
    docker container run -p 9999:8888 --name hello cloudnatived/demo:hello &
    curl -s http://localhost:9999

  #+end_src
** Container
   #+begin_src dockerfile :tangle myhello/Dockerfile
     FROM node:16-alpine3.11 AS deps

     WORKDIR /app/
     COPY package.json /app/
     COPY yarn.lock /app/
     RUN yarn install --frozen-lockfile

     FROM node:16-alpine3.11 AS build
     WORKDIR /app/
     COPY --from=deps /app/node_modules /app/node_modules
     COPY package.json /app/
     COPY tsconfig.json /app/
     COPY ./src/*.ts /app/src/
     RUN yarn compile
     RUN yarn build

     FROM alpine
     RUN apk update && \
	 apk add --no-cache libstdc++ libgcc ca-certificates && \
	 rm -rf /var/cache/apk/*
     WORKDIR /app/
     COPY --from=build /app/dist/ .
     CMD ./myhello

   #+end_src

Setting up typescript to compile in a Node JS container. See https://losikov.medium.com/part-1-project-initial-setup-typescript-node-js-31ba3aa7fbf1 for typescript setup.

Following https://medium.com/@evenchange4/deploy-a-commercial-next-js-application-with-pkg-and-docker-5c73d4af2ee.

#+begin_src typescript :tangle myhello/src/app.ts
  import express from "express";

  const app = express();
  const port = 3003;

  app.get("/", (req, res) => {
    res.send("Hello World!\n");
  });

  app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`);
  });
#+end_src

#+begin_src sh
  docker image build -t myhello .
  docker container run -p 3003:3003 myhello
  curl -s http://localhost:3003
#+end_src

*** Cleaning up
    #+begin_src sh
      yarn clean
    #+end_src

 I also had to stop and delete containers in Docker Desktop to clean up the containers on my machine.

** With Kubernetes

Had to do some additional steps to set up my kubernetes context.  See https://docs.docker.com/desktop/kubernetes/.

#+begin_src sh
  kubectl config get-contexts
  kubectl config use-context docker-desktop
#+end_src

** Running the pod

#+begin_src sh
kubectl run myhello --image=myhello:latest --port=3003 --labels app=myhello --image-pull-policy='Never'
#+end_src

I then set up port forwarding in =k9s=

#+begin_src sh
  k9s
  # F to enable port forwarding
  # C-k to kill the pod
#+end_src

* Ch4 Working with Kubernetes Objects
** Deployment
   #+begin_src sh
     cd k8s-demo
     kubectl apply -f deployment.yaml

   #+end_src
** Service
   #+begin_src sh
     cd k8s-demo
     kubectl apply -f service.yaml

   #+end_src
** Cleaning up
   #+begin_src sh
     kubectl delete -f k8s-demo/
     # or
     kubectl delete all --selector app=demo
   #+end_src
** Helm

   #+begin_src sh
     helm install demo helm3-demo/
     helm uninstall demo helm3-demo/
   #+end_src
* Ch 5 Managing Resources
** Namespaces
I thought I would need a =namespace.yaml= file to specify my app's namespace, but =helm= makes it easy when installing:

#+begin_src sh
  helm install demo helm3-demo/ --namespace demo --create-namespace
  # and clean up with
  helm uninstall demo --namespace demo
#+end_src


** Ok I've got my service running how do I talk to it from the outside world?
For trying to talk to services and pods see https://kubernetes.io/docs/concepts/services-networking/network-policies/ and https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

See also https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/.

The service.yaml defines a LoadBalancer exposing port 80 on the Cluster's external IP, which is localhost in this case (I think it's that by default).
#+begin_src yaml
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.container.port }}
    selector:
      app: {{ .Values.container.name }}
    type: LoadBalancer
#+end_src

You can see your Service's output by

#+begin_src sh
  curl -s http://localhost:80
#+end_src

You can go to the Services view in k9s to see this information.

* Ch 7 Kubernetes Power Tool
** Autocompleting kubectl commands
For zsh which I use at work
#+begin_src sh
  # Load the kubectl completion code for zsh[1] into the current shell
  source <(kubectl completion zsh)
  # Set the kubectl completion code for zsh[1] to autoload on startup
  kubectl completion zsh > "${fpath[1]}/_kubectl"
#+end_src
