apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: myhello:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3003
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "120Mi"
              cpu: "250m"
          livenessPorbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 3
            periodSeconds: 3
